version: '3.8'

services:
  nacos:
    image: qingpan/rnacos:stable
    container_name: rnacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "10848:10848"
    environment:
      - MODE=standalone  # 根据需要设置环境变量
    volumes:
      - nacos-data:/home/rnacos/data  # 挂载数据卷，保持数据持久性

volumes:
  nacos-data:
    driver: local
